# House Price Prediction - ML Pipeline
## София Кан | 11.06.2026

## 1. Постановка задачи

- Описание датасета и целевой переменной
- Тип задачи (классификация / регрессия)
- Метрики успеха

## 2. Загрузка данных и первичный осмотр

In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [23]:
housing_df = pd.read_csv('AmesHousing.csv', index_col='Order')

housing_df.head()

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
Order,,,,,,,,,,,,,,,,,,,,,
1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [24]:
housing_df.describe()

,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,2929.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,442.629566,...,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,455.590839,...,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,370.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,734.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [25]:
housing_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2930 entries, 1 to 2930
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PID              2930 non-null   int64
 1   MS SubClass      2930 non-null   int64
 2   MS Zoning        2930 non-null   object
 3   Lot Frontage     2440 non-null   float64
 4   Lot Area         2930 non-null   int64
 5   Street           2930 non-null   object
 6   Alley            198 non-null    object
 7   Lot Shape        2930 non-null   object
 8   Land Contour     2930 non-null   object
 9   Utilities        2930 non-null   object
 10  Lot Config       2930 non-null   object
 11  Land Slope       2930 non-null   object
 12  Neighborhood     2930 non-null   object
 13  Condition 1      2930 non-null   object
 14  Condition 2      2930 non-null   object
 15  Bldg Type        2930 non-null   object
 16  House Style      2930 non-null   object
 17  Overall Qual     2930 non-null   int64
 18  Overall Cond     2930 non-null   int64
 19  Year Built       2930 non-null   int64
 20  Year Remod/Add   2930 non-null   int64
 21  Roof Style       2930 non-null   object
 22  Roof Matl        2930 non-null   object
 23  Exterior 1st     2930 non-null   object
 24  Exterior 2nd     2930 non-null   object
 25  Mas Vnr Type     1155 non-null   object
 26  Mas Vnr Area     2907 non-null   float64
 27  Exter Qual       2930 non-null   object
 28  Exter Cond       2930 non-null   object
 29  Foundation       2930 non-null   object
 30  Bsmt Qual        2850 non-null   object
 31  Bsmt Cond        2850 non-null   object
 32  Bsmt Exposure    2847 non-null   object
 33  BsmtFin Type 1   2850 non-null   object
 34  BsmtFin SF 1     2929 non-null   float64
 35  BsmtFin Type 2   2849 non-null   object
 36  BsmtFin SF 2     2929 non-null   float64
 37  Bsmt Unf SF      2929 non-null   float64
 38  Total Bsmt SF    2929 non-null   float64
 39  Heating          2930 non-null   object
 40  Heating QC       2930 non-null   object
 41  Central Air      2930 non-null   object
 42  Electrical       2929 non-null   object
 43  1st Flr SF       2930 non-null   int64
 44  2nd Flr SF       2930 non-null   int64
 45  Low Qual Fin SF  2930 non-null   int64
 46  Gr Liv Area      2930 non-null   int64
 47  Bsmt Full Bath   2928 non-null   float64
 48  Bsmt Half Bath   2928 non-null   float64
 49  Full Bath        2930 non-null   int64
 50  Half Bath        2930 non-null   int64
 51  Bedroom AbvGr    2930 non-null   int64
 52  Kitchen AbvGr    2930 non-null   int64
 53  Kitchen Qual     2930 non-null   object
 54  TotRms AbvGrd    2930 non-null   int64
 55  Functional       2930 non-null   object
 56  Fireplaces       2930 non-null   int64
 57  Fireplace Qu     1508 non-null   object
 58  Garage Type      2773 non-null   object
 59  Garage Yr Blt    2771 non-null   float64
 60  Garage Finish    2771 non-null   object
 61  Garage Cars      2929 non-null   float64
 62  Garage Area      2929 non-null   float64
 63  Garage Qual      2771 non-null   object
 64  Garage Cond      2771 non-null   object
 65  Paved Drive      2930 non-null   object
 66  Wood Deck SF     2930 non-null   int64
 67  Open Porch SF    2930 non-null   int64
 68  Enclosed Porch   2930 non-null   int64
 69  3Ssn Porch       2930 non-null   int64
 70  Screen Porch     2930 non-null   int64
 71  Pool Area        2930 non-null   int64
 72  Pool QC          13 non-null     object
 73  Fence            572 non-null    object
 74  Misc Feature     106 non-null    object
 75  Misc Val         2930 non-null   int64
 76  Mo Sold          2930 non-null   int64
 77  Yr Sold          2930 non-null   int64
 78  Sale Type        2930 non-null   object
 79  Sale Condition   2930 non-null   object
 80  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(27), object(43)
memory usage: 1.8+ MB

In [ ]:
for i in housing_df.columns:
    result = f"{i}:  {(housing_df[i].notna().sum() / 2930) * 100} %"
    print(result)

PID:  100.0 %
MS SubClass:  100.0 %
MS Zoning:  100.0 %
Lot Frontage:  83.27645051194538 %
Lot Area:  100.0 %
Street:  100.0 %
Alley:  6.757679180887371 %
Lot Shape:  100.0 %
Land Contour:  100.0 %
Utilities:  100.0 %
Lot Config:  100.0 %
Land Slope:  100.0 %
Neighborhood:  100.0 %
Condition 1:  100.0 %
Condition 2:  100.0 %
Bldg Type:  100.0 %
House Style:  100.0 %
Overall Qual:  100.0 %
Overall Cond:  100.0 %
Year Built:  100.0 %
Year Remod/Add:  100.0 %
Roof Style:  100.0 %
Roof Matl:  100.0 %
Exterior 1st:  100.0 %
Exterior 2nd:  100.0 %
Mas Vnr Type:  39.419795221843 %
Mas Vnr Area:  99.2150170648464 %
Exter Qual:  100.0 %
Exter Cond:  100.0 %
Foundation:  100.0 %
Bsmt Qual:  97.26962457337885 %
Bsmt Cond:  97.26962457337885 %
Bsmt Exposure:  97.16723549488054 %
BsmtFin Type 1:  97.26962457337885 %
BsmtFin SF 1:  99.96587030716724 %
BsmtFin Type 2:  97.23549488054609 %
BsmtFin SF 2:  99.96587030716724 %
Bsmt Unf SF:  99.96587030716724 %
Total Bsmt SF:  99.96587030716724 %
Heating:  100.0 %
Heating QC:  100.0 %
Central Air:  100.0 %
Electrical:  99.96587030716724 %
1st Flr SF:  100.0 %
2nd Flr SF:  100.0 %
Low Qual Fin SF:  100.0 %
Gr Liv Area:  100.0 %
Bsmt Full Bath:  99.93174061433447 %
Bsmt Half Bath:  99.93174061433447 %
Full Bath:  100.0 %
Half Bath:  100.0 %
Bedroom AbvGr:  100.0 %
Kitchen AbvGr:  100.0 %
Kitchen Qual:  100.0 %
TotRms AbvGrd:  100.0 %
Functional:  100.0 %
Fireplaces:  100.0 %
Fireplace Qu:  51.46757679180888 %
Garage Type:  94.64163822525597 %
Garage Yr Blt:  94.57337883959043 %
Garage Finish:  94.57337883959043 %
Garage Cars:  99.96587030716724 %
Garage Area:  99.96587030716724 %
Garage Qual:  94.57337883959043 %
Garage Cond:  94.57337883959043 %
Paved Drive:  100.0 %
Wood Deck SF:  100.0 %
Open Porch SF:  100.0 %
Enclosed Porch:  100.0 %
3Ssn Porch:  100.0 %
Screen Porch:  100.0 %
Pool Area:  100.0 %
Pool QC:  0.4436860068259386 %
Fence:  19.522184300341298 %
Misc Feature:  3.6177474402730376 %
Misc Val:  100.0 %
Mo Sold:  100.0 %
Yr Sold:  100.0 %
Sale Type:  100.0 %
Sale Condition:  100.0 %
SalePrice:  100.0 %

## 3. EDA

   - Распределение целевой переменной
   - Распределения признаков (histplot, boxplot)
   - Корреляционная матрица (heatmap)
   - Выводы

## 4. Предобработка

    - Обработка пропусков
    - Кодирование категориальных переменных
    - Масштабирование
    - Feature engineering

## 5. Моделирование

    - Train / test split (stratify=y)
    - Модель 1: Logistic Regression
    - Модель 2: Decision Tree
    - Модель 3: Random Forest

## 6. Оценка и сравнение

    - Кросс-валидация (cross_val_score)
    - Сравнительная таблица метрик
    - Лучшая модель → RandomizedSearchCV

## 7. Анализ ошибок

    - Confusion matrix
    - Feature importance
    - Примеры ошибочных предсказаний

## 8. Выводы и следующие шаги

    - Какую модель выбрать и почему?
    - Что улучшить при большем времени?